export const tokenColorOrder = ['white', 'black', 'red', 'green', 'blue', 'gold']

export const tokenColorScheme: Record<string, Record<string, string>> = {
    'White': {
        'verylight': 'bg-slate-100',
        'background': 'bg-slate-200',
        'backgroundDark': 'bg-slate-300',
        'indicator': 'bg-slate-400',
        'text': 'text-slate-900',
        'textlight': 'text-slate-400',
        'border': 'border-slate-300',
        'checked': 'bg-slate-700',
    },
    'Black': {
        'verylight': 'bg-stone-100',
        'background': 'bg-stone-400',
        'backgroundDark': 'bg-stone-400',
        'indicator': 'bg-stone-500',
        'text': 'text-stone-950',
        'textlight': 'text-stone-600',
        'border': 'border-stone-600',
        'checked': 'bg-stone-700',
    },
    'Red': {
        'verylight': 'bg-red-100',
        'background': 'bg-red-400',
        'backgroundDark': 'bg-red-400',
        'indicator': 'bg-red-500',
        'text': 'text-red-950',
        'textlight': 'text-red-500',
        'border': 'border-red-400',
        'checked': 'bg-red-700',
    },
    'Green': {
        'verylight': 'bg-emerald-100',
        'background': 'bg-emerald-400',
        'backgroundDark': 'bg-emerald-400',
        'indicator': 'bg-emerald-500',
        'text': 'text-emerald-950',
        'textlight': 'text-emerald-500',
        'border': 'border-emerald-400',
        'checked': 'bg-emerald-700',
    },
    'Blue': {
        'verylight': 'bg-blue-100',
        'background': 'bg-blue-400',
        'backgroundDark': 'bg-blue-400',
        'indicator': 'bg-blue-500',
        'text': 'text-blue-950',
        'textlight': 'text-blue-500',
        'border': 'border-blue-400',
        'checked': 'bg-blue-700',
    },
    'Gold': {
        'verylight': 'bg-amber-100',
        'background': 'bg-amber-300',
        'backgroundDark': 'bg-amber-300',
        'indicator': 'bg-amber-500',
        'text': 'text-amber-950',
        'textlight': 'text-amber-500',
        'border': 'border-amber-400',
        'checked': 'bg-amber-700',
    },
}